name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: DotNet Restore
      run: dotnet restore
    
    - name: DotNet Build
      run: dotnet build --no-restore
      
    - name: DotNet Run Tests
      run: dotnet test --no-build --verbosity normal
      
    - name: DotNet Publish
      run: dotnet publish -c Release
      
    - name: Stop TrelloApi Service
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: sudo service TrelloApi stop
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.REMOTE_PORT }}
        password: ${{ secrets.REMOTE_PASS }}
        #passphrase: ${{ secrets.PASSPHRASE }}
        #privateKey: ${{ secrets.REMOTE_SSH_KEY }}
    - name: Copy to Server via rsync
      env:
        REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$REMOTE_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.REMOTE_PORT }} -o StrictHostKeyChecking=no" /home/runner/work/TrelloApi/TrelloApi/src/Cedeira.Trello.Api/bin/Release/net8.0/publish/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}
      
    #- name: Copy to Server via SCP
    #  uses: garygrossgarten/github-action-scp@release
    #  with:
    #    local: /home/runner/work/TrelloApi/TrelloApi/src/Cedeira.Trello.Api/bin/Release/net8.0/publish/
    #    remote: ${{ secrets.REMOTE_TARGET }}
    #    host: ${{ secrets.REMOTE_HOST }}
    #    username: ${{ secrets.REMOTE_USER }}
    #    port: ${{ secrets.REMOTE_PORT }}
    #    password: ${{ secrets.REMOTE_PASS }}
   #     rmRemote: true 
        #passphrase: ${{ secrets.PASSPHRASE }}
        #privateKey: ${{ secrets.REMOTE_SSH_KEY }}
   #   env:
   #     ASPNETCORE_ENVIRONMENT: Production
   #     debug: true
        
    - name: Start TrelloApi Service
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: sudo service TrelloApi start
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.REMOTE_PORT }}
        password: ${{ secrets.REMOTE_PASS }}
        #passphrase: ${{ secrets.PASSPHRASE }}
        #privateKey: ${{ secrets.REMOTE_SSH_KEY }}
